name: CI
on:
  push:
    branches: [ "main" ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:14-slim
    services:
      redis:
        image: redis
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm test
        env: 
          redis: redis://redis
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.REGISTRY }}/irvin:latest
      - name: REST API with curl
        run: |
          curl -H "Authorization: Bearer ${{ secrets.WATCHTOWER }}" https://${{ secrets.WATCHTOWER_URL }}/v1/update
